// Generated by CoffeeScript 1.10.0
(function() {
  window.Post = chrome.runtime.sendMessage;

  window.addEventListener('error', (function(error) {
    return Debug(error);
  }), false);

  Settings.init(function() {
    KeyEvent.init();
    return $(function() {
      var func, i, len, ref;
      ref = [Zoom.init, Custom.runJS, Custom.loadCSS];
      for (i = 0, len = ref.length; i < len; i++) {
        func = ref[i];
        func.call();
      }
    });
  });

}).call(this);
