// Generated by CoffeeScript 1.10.0
(function() {
  var openChromeStore, openIssuesPage, openSourcePage;

  openSourcePage = function() {
    return openUrl('https://github.com/jinzhu/vrome');
  };

  openChromeStore = function() {
    return openUrl('https://chrome.google.com/webstore/detail/godjoomfiimiddapohpmfklhgmbfffjj/details');
  };

  openIssuesPage = function() {
    return openUrl('https://github.com/jinzhu/vrome/issues');
  };

  $(function() {
    $('.openOptionsFeatures').click(function() {
      return openOptions('features');
    });
    $('.openOptionsSetting').click(function() {
      return openOptions('setting');
    });
    $('.openOptionsChangelog').click(function() {
      return openOptions('changelog');
    });
    $('.openOptionsDonates').click(function() {
      return openOptions('donates');
    });
    $('.openSourcePage').click(openSourcePage);
    $('.openChromeStore').click(openChromeStore);
    return $('.openIssuesPage').click(openIssuesPage);
  });

  Settings.init(function() {
    return $(function() {
      return $('.version').text(Settings.get('version'));
    });
  });

}).call(this);
