// Generated by CoffeeScript 1.10.0
(function() {
  chrome.tabs.onCreated.addListener(function(tab) {
    return Tab.lastOpenTabs.push(tab);
  });

  chrome.tabs.onActivated.addListener(function(info) {
    if (!Tab.currentTab || info.tabId !== Tab.currentTab.id) {
      chrome.tabs.get(info.tabId, function(tab) {
        if (tab) {
          Tab.previousTab = Tab.currentTab;
          return Tab.currentTab = tab;
        }
      });
    }
    return Vrome.setStatus(info.tabId);
  });

  chrome.tabs.onRemoved.addListener(function(tabId) {
    var tab;
    tab = Tab.currentTab;
    if ((tab != null ? tab.id : void 0) === tabId) {
      return Tab.addToClosedTabs(tab);
    }
  });

}).call(this);
