// Generated by CoffeeScript 1.10.0
(function() {
  window.Bookmark = (function() {
    function Bookmark() {}

    Bookmark.search = function(msg) {
      var drawDialog;
      drawDialog = function(bookmarks) {
        return Post(msg.tab, {
          action: 'Dialog.draw',
          urls: bookmarks,
          keyword: msg.keyword
        });
      };
      if (msg.keyword === '') {
        return chrome.bookmarks.getRecent(20, drawDialog);
      } else {
        return chrome.bookmarks.search(msg.keyword, drawDialog);
      }
    };

    return Bookmark;

  })();

}).call(this);
