// Generated by CoffeeScript 1.10.0
(function() {
  window.Develop = (function() {
    var TIME, checkReloadExtension, latestVersion;

    function Develop() {}

    latestVersion = null;

    TIME = 500;

    checkReloadExtension = function() {
      return $.post(getLocalServerUrl(), JSON.stringify({
        method: 'get_latest_version'
      })).success(function(response) {
        if (latestVersion !== null && latestVersion !== response) {
          Develop.reloadExtension();
        }
        if (latestVersion === null) {
          chrome.tabs.reload({
            bypassCache: true
          });
        }
        return latestVersion = response;
      });
    };

    Develop.init = function() {
      if (Option.get('debug')) {
        return setInterval(checkReloadExtension, TIME);
      }
    };

    Develop.reloadExtension = function() {
      return chrome.tabs.query({
        url: 'chrome://extensions-frame/',
        currentWindow: true
      }, function(tabs) {
        if (tabs.length > 0) {
          return chrome.tabs.reload(tabs[0].id, {
            bypassCache: true
          });
        } else {
          return chrome.tabs.create({
            url: 'chrome://extensions-frame/',
            active: false,
            pinned: true
          });
        }
      });
    };

    return Develop;

  })();

}).call(this);
