// Generated by CoffeeScript 1.10.0
(function() {
  window.Editor = (function() {
    var code;

    function Editor() {}

    code = "CmdBox.set({ title: 'Failed to open external Editor, Please check Vrome WIKI opened in a new tab for how to do', timeout : 15000 });";

    Editor.open = function(msg) {
      var params, post;
      params = JSON.stringify({
        method: 'open_editor',
        data: msg.data,
        col: msg.col,
        line: msg.line
      });
      post = $.post(getLocalServerUrl(), params);
      post.fail(function() {
        runScript({
          tab: msg.tab,
          code: code
        });
        return chrome.tabs.create({
          url: 'https://github.com/jinzhu/vrome/wiki/Support-External-Editor',
          index: msg.tab.index + 1,
          active: false
        });
      });
      return post.done(function(data) {
        return Post(msg.tab, {
          action: msg.callbackAction,
          editId: msg.editId,
          value: data
        });
      });
    };

    return Editor;

  })();

}).call(this);
