// Generated by CoffeeScript 1.10.0
(function() {
  var modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

  window.Frame = (function() {
    var currentFrameUrls, nextUrl;

    function Frame() {}

    currentFrameUrls = {};

    nextUrl = function(frames, currentFrameUrl, count) {
      var currentIndex, frame, frameUrls, newIndex, uniqueUrls;
      frameUrls = (function() {
        var i, len, ref, results;
        results = [];
        for (i = 0, len = frames.length; i < len; i++) {
          frame = frames[i];
          if ((ref = frame.url) !== 'doubleclick.' && ref !== 'qzone.qq.com' && ref !== 'plusone.google.com' && ref !== 'about:blank') {
            results.push(frame.url);
          }
        }
        return results;
      })();
      uniqueUrls = $.unique(frameUrls).reverse();
      currentIndex = uniqueUrls.indexOf(currentFrameUrl);
      newIndex = modulo(currentIndex + count, uniqueUrls.length);
      return uniqueUrls[newIndex];
    };

    Frame.next = function(msg) {
      return chrome.webNavigation.getAllFrames({
        tabId: msg.tab.id
      }, function(frames) {
        currentFrameUrls[msg.tab.id] = nextUrl(frames, currentFrameUrls[msg.tab.id], msg.count);
        return Post(msg.tab, {
          action: 'Frame.select',
          href: currentFrameUrls[msg.tab.id]
        });
      });
    };

    return Frame;

  })();

}).call(this);
