// Generated by CoffeeScript 1.10.0
(function() {
  window.History = (function() {
    function History() {}

    History.search = function(msg) {
      return chrome.history.search({
        text: msg.keyword,
        startTime: 0
      }, function(history) {
        return Post(msg.tab, {
          action: 'Dialog.draw',
          urls: history,
          keyword: msg.keyword
        });
      });
    };

    return History;

  })();

}).call(this);
