// Generated by CoffeeScript 1.10.0
(function() {
  var checkNewVersion;

  window.Post = function(tab, message) {
    return chrome.tabs.sendMessage(tab.id, message);
  };

  window.runScript = function(msg) {
    return chrome.tabs.executeScript(msg.tab.id, {
      code: msg.code
    });
  };

  window.addEventListener('error', (function(error) {
    return Debug(error);
  }), false);

  checkNewVersion = function() {
    return $.get(chrome.extension.getURL('manifest.json')).done(function(data) {
      data = JSON.parse(data);
      if (Settings.get('version') !== data.version) {
        openOptions('changelog');
      }
      return Settings.add({
        version: data.version
      });
    });
  };

  Settings.init(function() {
    checkNewVersion();
    Vromerc.init();
    return Develop.init();
  });

}).call(this);
