// Generated by CoffeeScript 1.10.0
(function() {
  window.getLocalServerUrl = function() {
    return "http://127.0.0.1:" + (Option.get('server_port'));
  };

  window.desc = function(func, description) {
    return func.description = description;
  };

  window.fixRelativePath = function(url, currentUrl) {
    var i, len, location, path, pathname, ref;
    if (url.isValidURL()) {
      return url;
    }
    location = document.createElement('a');
    location.href = currentUrl || document.location.href;
    if (url[0] === '/') {
      return location.origin + url;
    }
    if (url.endsWith('..')) {
      url += '/';
    }
    pathname = location.origin + location.pathname.replace(/\/+/g, '/');
    ref = url.split('..');
    for (i = 0, len = ref.length; i < len; i++) {
      path = ref[i];
      if (path[0] === '/') {
        pathname = pathname.replace(/\/[^\/]*\/?$/, '') + path;
      } else if (path.startsWith('./')) {
        pathname = pathname.replace(/\/$/, '') + path.substr(1);
      }
    }
    return pathname;
  };

  window.openUrl = function(url) {
    return chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      return Tab.openUrl({
        url: url,
        newTab: true,
        active: true,
        tab: tabs[0]
      });
    });
  };

  window.openOptions = function(params) {
    var url;
    url = "background/html/options.html" + (params ? "#" + params : '');
    return openUrl(chrome.extension.getURL(url));
  };

  window.isEditableElement = function(element) {
    return element.nodeType === 1 && ($(element).is('input, textarea, select') || (element.getAttribute('contenteditable') != null));
  };

}).call(this);
