// Generated by CoffeeScript 1.10.0
(function() {
  window.AutoLink = (function() {
    var URL_REGEXP, textNodes;

    function AutoLink() {}

    URL_REGEXP = /(((https?|ftp|file):\/\/)?([\w]{2,}\.)+[\w]{2,5}(\/[\S]+)*)/g;

    textNodes = function(elems) {
      return elems.filter(function(e) {
        var ref;
        return ((ref = e.data) != null ? ref.match(URL_REGEXP) : void 0) && e.nodeType === 3 && !$(e).is('input, textarea');
      });
    };

    AutoLink.makeLink = function(elems) {
      var $elem, elem, i, len, value;
      if (elems == null) {
        elems = null;
      }
      elems = textNodes(elems || $('*:visible').not('iframe').contents());
      for (i = 0, len = elems.length; i < len; i++) {
        elem = elems[i];
        $elem = $(elem);
        if ($elem.parent().prop('tagName') !== 'A') {
          value = $elem.text().replace(URL_REGEXP, function($0, $1) {
            return "<a href='" + ($1.getValidURL()) + "'>" + $1 + "</a>";
          });
          $elem.after(value).remove();
        }
      }
    };

    desc(AutoLink.makeLink, 'Transforms URLs into clickable links');

    return AutoLink;

  })();

}).call(this);
