// Generated by CoffeeScript 1.10.0
(function() {
  window.Bookmark = (function() {
    var search;

    function Bookmark() {}

    search = function(keyword) {
      return Post({
        action: 'Bookmark.search',
        keyword: keyword
      });
    };

    Bookmark.start = function(newTab) {
      return Dialog.start({
        title: 'Bookmark',
        search: search,
        newTab: newTab
      });
    };

    desc(Bookmark.start, 'Filter bookmarks with keyword (support Dialog extend mode)');

    Bookmark.newTabStart = function() {
      return Bookmark.start(true);
    };

    return Bookmark;

  })();

}).call(this);
