// Generated by CoffeeScript 1.10.0
(function() {
  window.Debug = function(str) {
    var err, error;
    try {
      if (typeof str === 'object' && str.hasOwnProperty('stack') && str.hasOwnProperty('message')) {
        str = str.message + "\n\n" + str.stack;
      }
      if ($.isFunction(str)) {
        str = str.toString();
      }
      console.log(str);
      return Post({
        action: 'Debug',
        message: str
      });
    } catch (error) {
      err = error;
      return console.log(err);
    }
  };

}).call(this);
