// Generated by CoffeeScript 1.10.0
(function() {
  window.Frame = (function() {
    function Frame() {}

    Frame.select = function(msg) {
      var area, code, originalBorder;
      if (location.href === msg.href) {
        area = innerWidth * innerHeight;
        if (area <= 100) {
          return Post({
            action: 'Frame.next',
            count: 1
          });
        }
        window.focus();
        originalBorder = document.body.style.border;
        document.body.scrollIntoViewIfNeeded();
        document.body.style.border = '5px solid yellow';
        setTimeout((function() {
          return document.body.style.border = originalBorder;
        }), 200);
        code = "CmdBox.set({ title: 'Switched Frame To:" + document.location.href + "', timeout: 2000 });";
        return Post({
          action: 'runScript',
          code: code
        });
      }
    };

    Frame.next = function() {
      return Post({
        action: 'Frame.next',
        count: times()
      });
    };

    desc(Frame.next, 'Next {count} frame');

    Frame.prev = function() {
      return Post({
        action: 'Frame.next',
        count: -times()
      });
    };

    desc(Frame.prev, 'Previous {count} frame');

    return Frame;

  })();

}).call(this);
