// Generated by CoffeeScript 1.10.0
(function() {
  window.Help = (function() {
    var escape, maps;

    function Help() {}

    maps = [];

    escape = function(value) {
      return value.toString().escape();
    };

    Help.add = function(key, funcName, func, mode) {
      if (func.description) {
        return maps.push([escape(key), escape(funcName), escape(func.description), mode]);
      }
    };

    Help.show = function() {
      var helpBox, map, resultBox, results;
      results = "<tr class='head'><td>Value</td><td>Description</td><td>Modes</td></tr>";
      results += ((function() {
        var i, len, results1;
        results1 = [];
        for (i = 0, len = maps.length; i < len; i++) {
          map = maps[i];
          results1.push("<tr><td>" + map[0] + "</td><td>" + map[2] + "</td><td>" + map[3] + "</td></tr>");
        }
        return results1;
      })()).join();
      resultBox = $('<div>', {
        id: '__vrome_help_box',
        html: "<table>" + results + "</table>"
      });
      helpBox = $('<div>', {
        id: '__vrome_help_overlay',
        html: resultBox
      });
      return $(document.documentElement).append(helpBox);
    };

    desc(Help.show, 'Open help page');

    Help.hide = function(reset) {
      return $('#__vrome_help_overlay').remove();
    };

    return Help;

  })();

}).call(this);
