// Generated by CoffeeScript 1.10.0
(function() {
  window.History = (function() {
    var search;

    function History() {}

    search = function(keyword) {
      return Post({
        action: 'History.search',
        keyword: keyword
      });
    };

    History.start = function(newTab) {
      return Dialog.start({
        title: 'History',
        search: search,
        newTab: newTab
      });
    };

    desc(History.start, 'Filter History with keyword (support Dialog extend mode)');

    History.newTabStart = function() {
      return History.start(true);
    };

    History.back = function() {
      return history.go(-times());
    };

    desc(History.back, 'Go {count} pages back');

    History.forward = function() {
      return history.go(times());
    };

    desc(History.forward, 'Go {count} pages forward');

    return History;

  })();

}).call(this);
