// Generated by CoffeeScript 1.10.0
(function() {
  window.Links = (function() {
    var i, len, open, ref, url;

    function Links() {}

    open = function(url) {
      return Post({
        action: 'Tab.openUrl',
        url: url,
        newTab: CmdBox.get().content.indexOf('!') !== -1
      });
    };

    Links.downloads = function() {
      return open('chrome://downloads/');
    };

    Links.history = function() {
      return open('chrome://history/');
    };

    Links.chrome_help = function() {
      return open('chrome://help/');
    };

    Links.bookmarks = function() {
      return open('chrome://bookmarks/');
    };

    Links.settings = function() {
      return open('chrome://settings/');
    };

    Links.extensions = function() {
      return open('chrome://extensions/');
    };

    Links.github = function() {
      return open('https://github.com/jinzhu/vrome');
    };

    Links.issues = function() {
      return open('https://github.com/jinzhu/vrome/issues');
    };

    Links.options = function() {
      return open('/background/html/options.html');
    };

    ref = ['downloads', 'bookmarks', 'history', 'chrome_help', 'settings', 'extensions', 'github', 'issues', 'options'];
    for (i = 0, len = ref.length; i < len; i++) {
      url = ref[i];
      desc(Links[url], "Open " + url + ",! open in new page");
    }

    return Links;

  })();

}).call(this);
