// Generated by CoffeeScript 1.10.0
(function() {
  window.Window = (function() {
    function Window() {}

    Window.create = function() {
      return Post({
        action: 'Window.create'
      });
    };

    desc(Window.create, 'Open a new window');

    Window.close = function() {
      return Post({
        action: 'Window.close'
      });
    };

    desc(Window.close, 'Close current window');

    Window.closeAll = function() {
      return Post({
        action: 'Window.closeAll'
      });
    };

    desc(Window.closeAll, 'Close all windows (quitall)');

    Window.only = function() {
      return Tab.close({
        type: 'otherWindows'
      });
    };

    desc(Window.only, 'Close other windows');

    Window.saveAs = function(msg) {
      var filename;
      if (msg != null ? msg.filename : void 0) {
        return CmdBox.set({
          title: "Downloaded as '" + msg.filename + "'",
          timeout: 4000
        });
      } else {
        filename = CmdBox.get().argument;
        CmdBox.remove();
        return setTimeout(Post, 500, {
          action: 'Window.savePage',
          filename: filename
        });
      }
    };

    desc(Window.saveAs, 'Save page as');

    Window.capture = function(msg) {
      if (msg != null ? msg.url : void 0) {
        Clipboard.copy(msg.url);
        return CmdBox.set({
          title: "Captured current window,<a href='" + msg.url + "' target='_blank'>Click to see the image</a>",
          timeout: 8000
        });
      } else {
        CmdBox.remove();
        return setTimeout(Post, 500, {
          action: 'Window.capture'
        });
      }
    };

    desc(Window.capture, 'Capture visible tab');

    return Window;

  })();

}).call(this);
